# Specifies the ESLint parser
parser: "@typescript-eslint/parser"
extends:
  # Uses the recommended rules from the @typescript-eslint/eslint-plugin
  - "plugin:@typescript-eslint/recommended"
  # Enables eslint-plugin-prettier and eslint-config-prettier.
  # This will display prettier errors as ESLint errors.
  # Make sure this is always the last configuration in the extends array.
  - "plugin:prettier/recommended"
parserOptions:
  # Allows for the parsing of modern ECMAScript features
  ecmaVersion: 2018
  # Allows for the use of imports
  sourceType: "module"
rules:
  # enables functions hoisting without eslint complaining
  "@typescript-eslint/no-use-before-define": off
  # enables type inference without eslint complaining
  "@typescript-eslint/explicit-function-return-type": off