name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: yarn tsc --noEmit
      - run: yarn test
      - run: yarn lint
