name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - run: yarn install
    - run: yarn test
    - run: yarn tsc --noEmit
    - run: yarn lint
