name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn tsc --noEmit
    - run: yarn test
    - run: yarn lint
