name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn tsc --noEmit
      - run: yarn test
      - run: yarn lint
